Vienauto Web/Vienauto.Mobile/Controllers/ModelController.cs
using System;
using System.IO;
using System.Web.Mvc;
using Common.Core.Mvc;
using Vienauto.Entity.Enums;
using Vienauto.Interface.Dto;
using System.Threading.Tasks;
using Common.Core.Data.Paging;
using Common.Core.Mvc.Attribute;
using System.Collections.Generic;
using Vienauto.Interface.Services;
using Vienauto.Mobile.Models.View;
using Vienauto.Mobile.Models.Form;
using Vienauto.Mobile.Configuration;
using Vienauto.Interface.AsyncServices;
using Vienauto.Mobile.Configuration.SEO;
using Vienauto.Mobile.Configuration.SEO.Model;

namespace Vienauto.Mobile.Controllers
{
    public class ModelController : BaseController
    {
        private readonly IModelService _modelService;
        private readonly IModelAsyncService _modelAsyncService;

        public ModelController(IModelService modelService, IModelAsyncService modelAsyncService)
        {
            _modelService = modelService;
            _modelAsyncService = modelAsyncService;
        }

        public async Task<ActionResult> Index(string manufacturer, string model, string year)
        {
            var error = string.Empty;
            var modelInformationView = new ModelDetail();
            var modelInformationDto = await _modelAsyncService.GetModelStandardInformationAsync(DecodeUrl(manufacturer), DecodeUrl(model), DecodeUrl(year), 0, UserId);
            if (!modelInformationDto.HasErrors)
            {
                //Embbed SEO
                var modelDetailParameter = new ModelModule
                {
                    Manufacturer = manufacturer,
                    Model = model,
                    Year = year
                };
                AssignSEOInfo(modelDetailParameter, new SEOModelIndex());
                EmbbedSEO();
                //End Embbed SEO
                return View(modelInformationView.TransForm(modelInformationDto.Target));
            }
            else if (modelInformationDto.Errors.Exists(e => e.Code == ErrorCode.UndefinedModel))
                error = "Không tồn tại dòng xe đã chọn.";
            return ErrorContent(error);
        }

        public async Task<ActionResult> Review(int manufacturerId, int modelId, int yearId)
        {
            var modelDetail = await _modelAsyncService.GetModelReviewDetailAsync(manufacturerId, modelId, yearId, UserId);
            if (!modelDetail.HasErrors)
            {
                //Embbed SEO
                var modelDetailParameter = new ModelModule
                {
                    Manufacturer = modelDetail.Target.Brand,
                    Model = modelDetail.Target.Model,
                    Year = modelDetail.Target.Year
                };
                AssignSEOInfo(modelDetailParameter, new SEOModelReview());
                EmbbedSEO();
                //End Embbed SEO
                var detailModeModel = new ModelReviewDetail().TransForm(modelDetail.Target);
                return View(detailModeModel);
            }
            return View(new ModelReviewDetail());
        }

        public async Task<ActionResult> Detail(string manufacturer, string model, string year, int carId = 0)
        {
            var modelInformationView = new ModelDetail();
            var modelInformationDto = await _modelAsyncService.GetModelStandardInformationAsync(DecodeUrl(manufacturer), DecodeUrl(model), DecodeUrl(year), carId, UserId);
            if (!modelInformationDto.HasErrors)
            {
                //Embbed SEO
                var modelDetailParameter = new ModelModule
                {
                    Manufacturer = manufacturer,
                    Model = model,
                    Year = year
                };
                AssignSEOInfo(modelDetailParameter, new SEOModelDetail());
                EmbbedSEO();
                //End Embbed SEO
                return View(modelInformationView.TransForm(modelInformationDto.Target));
            }
            else if (modelInformationDto.Errors.Exists(e => e.Code == ErrorCode.UndefinedModel))
            {
                return ErrorContent("Không tồn tại dòng xe đã chọn.");
            }
            return View();
        }

        public async Task<ActionResult> GetModelDetailOverview(int carId)
        {
            var error = string.Empty;
            var modelDetailOverviewViewModel = new OverviewModelDetail();
            var modelDetailOverviewDto = await _modelAsyncService.GetOverviewAsync(carId);
            if (!modelDetailOverviewDto.HasErrors)
                return PartialView("_ModelDetailOverviewContent", modelDetailOverviewViewModel.TransForm(modelDetailOverviewDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailEngine(int carId)
        {
            var error = string.Empty;
            var modelDetailEngineViewModel = new EngineModelDetail();
            var modelDetailEngineDto = await _modelAsyncService.GetEngineAsync(carId);
            if (!modelDetailEngineDto.HasErrors)
                return PartialView("_ModelDetailEngineContent", modelDetailEngineViewModel.TransForm(modelDetailEngineDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailSafety(int carId)
        {
            var error = string.Empty;
            var modelDetailSafetyViewModel = new SafetyModelDetail();
            var modelDetailSafetyDto = await _modelAsyncService.GetSafetyAsync(carId);
            if (!modelDetailSafetyDto.HasErrors)
                return PartialView("_ModelDetailSafetyContent", modelDetailSafetyViewModel.TransForm(modelDetailSafetyDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailEntertainment(int carId)
        {
            var error = string.Empty;
            var modelDetailEntertainmentViewModel = new EntertainmentModelDetail();
            var modelDetailEntertainmentDto = await _modelAsyncService.GetEntertainmentAsync(carId);
            if (!modelDetailEntertainmentDto.HasErrors)
                return PartialView("_ModelDetailEntertainmentContent", modelDetailEntertainmentViewModel.TransForm(modelDetailEntertainmentDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailInterior(int carId)
        {
            var error = string.Empty;
            var modelDetailInteriorViewModel = new InteriorModelDetail();
            var modelDetailInteriorDto = await _modelAsyncService.GetInteriorAsync(carId);
            if (!modelDetailInteriorDto.HasErrors)
                return PartialView("_ModelDetailInteriorContent", modelDetailInteriorViewModel.TransForm(modelDetailInteriorDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailExterior(int carId)
        {
            var error = string.Empty;
            var modelDetailExteriorViewModel = new ExteriorModelDetail();
            var modelDetailExteriorDto = await _modelAsyncService.GetExteriorAsync(carId);
            if (!modelDetailExteriorDto.HasErrors)
                return PartialView("_ModelDetailExteriorContent", modelDetailExteriorViewModel.TransForm(modelDetailExteriorDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailColor(int carId)
        {
            var error = string.Empty;
            var modelDetailColorViewModel = new ColorModelDetail();
            var modelDetailColorDto = await _modelAsyncService.GetColorAsync(carId);
            if (!modelDetailColorDto.HasErrors)
                return PartialView("_ModelDetailColorContent", modelDetailColorViewModel.TransForm(modelDetailColorDto.Target));
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> GetModelDetailImage(int carId)
        {
            var error = string.Empty;
            var modelDetailImageViewModel = new ImageModelDetail();
            var modelDetailImageDto = await _modelAsyncService.GetImageAsync(carId);
            if (!modelDetailImageDto.HasErrors)
            {
                modelDetailImageViewModel = modelDetailImageViewModel.TransForm(modelDetailImageDto.Target);
                int dem1 = GetNumberFilesInFolder("data-xe/" + modelDetailImageViewModel.PathImages);
                if (dem1 > 0)
                {
                    modelDetailImageViewModel.ImageList = FetchSlideImage("data-xe/" + modelDetailImageViewModel.PathImages, "");
                }
                else
                {
                    int dem2 = GetNumberFilesInFolder("data-dongxe-serv/" + modelDetailImageViewModel.PathImages);
                    modelDetailImageViewModel.ImageList = FetchSlideImage("data-dongxe-serv/" + modelDetailImageViewModel.PathImages, "");
                }
                return PartialView("_ModelDetailImageContent", modelDetailImageViewModel);
            }
            else
                error = ErrorMessage.ERROR_CONTACT_ADMIN;
            return ErrorContent(error);
        }

        public async Task<ActionResult> SameVersion(string manufacturer, string model, string year, int carId = 0)
        {
            var sameStyleViewModel = new ModelSameVersion();
            var modelDto = await _modelAsyncService.GetModelStandardInformationAsync(DecodeUrl(manufacturer), DecodeUrl(model), DecodeUrl(year), carId, UserId);
            if (!modelDto.HasErrors)

Vienauto Web/Vienauto.Mobile/Views/Sell/Detail.cshtml
@using Vienauto.Mobile.Configuration;
@using Vienauto.Mobile.Models.View.CarForSell;
@model CarForSellDetail

@Styles.Render(AppSetting.BundleCssSellPath)
@Scripts.Render(AppSetting.BundleJsSellPath)

<div data-role="content" class="ui-content sell-content" role="main">
    @Html.HiddenFor(x => x.ManufacturerId, new { id = "current-manufactureId" })
    @Html.HiddenFor(x => x.ModelId, new { id = "current-modelId" })
    @Html.HiddenFor(x => x.YearId, new { id = "current-yearId" })
    @Html.HiddenFor(x => x.CarId, new { id = "current-carId" })
    @Html.HiddenFor(x => x.ProductId, new { id = "current-productId" })
    <h2 class="price-mileage">
        <a href="@Url.Action("Index", "Model", new {
                manufacturer = Model.ManufacturerName,
                model = Model.ModelName,
                year = Model.YearName })">
            @Model.YearName @Model.ManufacturerName @Model.ModelName
        </a>
    </h2>
    <h4 class="price-mileage">@Model.CarName</h4>
    <h4 class="price-mileage">@Model.StyleName</h4>
    <p class="price-mileage">
        <img src="@Model.Avatar"
             alt="@Model.YearName @Model.ManufacturerName @Model.ModelName" class="vehicle-photo">
    </p>
    <div class="common-model-info price-mileage">
        <div class="container-fluid">
            <hr/>
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Mã xe:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Hãng:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Đời xe:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Kiểu dáng:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Xuất xứ:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Tình trạng:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Số VIN:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Bảo hành:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Giá bán:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
            <hr />
            <div class="row sell-describe">
                <div class="col-xs-5">
                    Chiết khấu DL:
                </div>
                <div class="col-xs-7">
                    <strong>ABC</strong>
                </div>
            </div>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="active">
            <a data-toggle="tab" href="#section-overview">Tổng quan</a>
        </li>
        <li>
            <a data-toggle="tab" href="#section-technology">Thông số</a>
        </li>
        <li>
            <a data-toggle="tab" href="#section-image">Hình ảnh</a>
        </li>
        <li>
            <a data-toggle="tab" href="#section-style">Giải trí / Màu sắc</a>
        </li>
        <li>
            <a data-toggle="tab" href="#section-view">Nội ngoại thất</a>
        </li>
    </ul>
    <div class="tab-content">
        <div id="section-overview" class="tab-pane fade in active">
        </div>
        <div id="section-technology" class="tab-pane fade">
            <ul class="nav nav-pills">
                <li class="active">
                    <a data-toggle="tab" href="#section-engine">Động cơ</a>
                </li>
                <li><a data-toggle="tab" href="#section-safety">An toàn</a></li>
            </ul>
            <div class="tab-content">
                <div id="section-engine" class="tab-pane fade in active">
                </div>
                <div id="section-safety" class="tab-pane fade">
                </div>
            </div>
        </div>
        <div id="section-image" class="tab-pane fade">
        </div>
        <div id="section-style" class="tab-pane fade">
            <ul class="nav nav-pills">
                <li class="active"><a data-toggle="tab" href="#section-entertainment">Giải trí</a></li>
                <li><a data-toggle="tab" href="#section-color">Màu sắc</a></li>
            </ul>
            <div class="tab-content">
                <div id="section-entertainment" class="tab-pane fade in active">
                </div>
                <div id="section-color" class="tab-pane fade">
                </div>
            </div>
        </div>
        <div id="section-view" class="tab-pane fade">
            <ul class="nav nav-pills">
                <li class="active"><a data-toggle="tab" href="#section-interior">Nội thất</a></li>
                <li><a data-toggle="tab" href="#section-exterior">Ngoại thất</a></li>
            </ul>
            <div class="tab-content">
                <div id="section-interior" class="tab-pane fade in active">
                </div>
                <div id="section-exterior" class="tab-pane fade">
                </div>
            </div>
        </div>
    </div>
</div>

Vienauto Web/Vienauto.Mobile/Views/Sell/_Inform.cshtml
<p class="thongbao">Thông số trên chỉ mang tính chất tham khảo, có thể khác ở từng phiên bản của dòng xe</p>

Vienauto Web/Vienauto.Mobile/Views/Sell/_NoData.cshtml
<div class="js-manufacturerIncentives">
    <div class="js-mi-widget">
        <div class="alert-message notification">
            <span>
                Hiện tại chưa có dữ liệu.
            </span>
            <p>Vienauto.com sẽ cập nhật thông tin sớm nhất có thể.</p>
        </div>
    </div>
</div>

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailColorContent.cshtml
@using Vienauto.Mobile.Models.View
@model ColorModelDetail

@if (Model != null && !string.IsNullOrEmpty(Model.Color))
{
    @Html.Partial("_Inform")
    <div class="embed-responsive embed-responsive-16by9" style="display: none;">
        @Html.Raw(Model.Color)
    </div>                
}
else
{
    @Html.Partial("_NoData")
}

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailEngineContent.cshtml
@using Vienauto.Mobile.Models.View
@model EngineModelDetail

<div class="pad-box">    
    @if (Model != null)
    {
        @Html.Partial("_Inform")
        <div class="row">
            <div class="col-md-4">
                <ul class="list">
                    <li>Động cơ: @Model.EngineName </li>
                    <li>Kiểu động cơ: @Model.EngineType</li>
                    <li>Tỷ số nén: @Model.CompressionRatio</li>
                    <li>Kiểu dẫn động: @Model.DrivingType</li>
                    <li>Loại hộp số: @Model.TranmissionType</li>
                    <li>Nhiên liệu: @Model.FuelType</li>
                    <li>Tiêu hao nhiên liệu (TP): @Model.FuelEconomyCity lít</li>
                    <li>Tiêu hao nhiên liệu (Cao tốc): @Model.FuelEconomyHighway lít</li>
                    <li>Dung tích bình nhiên liệu: @Model.Locking lít</li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list">
                    <li>Cơ cấu van: @Model.EngineValvetrain</li>
                    <li>Hệ thống cân bằng điện tử (ESS): @Model.ESS</li>
                    <li>Hệ thống phanh điện tử (EBD): @Model.EBD</li>
                    <li>Điều khiển từ xa: @Model.RemoteVehicle</li>
                    <li>Cấp số: @Model.Tranmission</li>
                    <li>Chiều dài: @Model.ExteriorLength mm</li>
                    <li>Chiều rộng: @Model.ExteriorWidth mm</li>
                    <li>Chiều cao: @Model.ExteriorHeight mm</li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list">
                    <li>Mã lực: @Model.HorsePower</li>
                    <li>Mômen xoắn: @Model.Torque</li>
                    <li>Hệ số cản: @Model.DragCoeficient</li>
                    <li>Thời gian tăng tốc (0-100km/h): @Model.TimeSpeed s</li>
                    <li>Tốc độ tối đa: @Model.Km km/h</li>
                    <li>Trọng lượng không tải: @Model.CurbWeight kg</li>
                    <li>Trọng lượng toàn tải: @Model.GVWR kg</li>
                </ul>
            </div>
        </div>
    }
    else
    {
        @Html.Partial("_NoData")
    }
</div>

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailEntertainmentContent.cshtml
@using Vienauto.Mobile.Models.View
@model EntertainmentModelDetail

<div class="pad-box">    
    @if (Model != null)
    {
        @Html.Partial("_Inform")
        <div class="row">
            <div class="col-md-6">
                <ul class="list">
                    <li>Radio: @Model.Radio</li>
                    <li>CD Player: @Model.CDPlayer</li>
                    <li>DVD Audio: @Model.DVDAudio</li>
                    <li>Nhận dạng giọng nói: @Model.SpeechRecognition</li>
                    <li>Loa: @Model.Speakers</li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list">
                    <li>Bộ khuếch đại: @Model.Amplifier</li>
                    <li>Hỗ trợ Bluetooth: @Model.BluetoothCompatibility</li>
                    <li>Hỗ trợ Wifi: @Model.WifiCompatibility</li>
                    <li>Hỗ trợ 3G: @Model.ThreeGCompatibility</li>
                    <li>Định vị toàn cầu: @Model.GPSCompatibility</li>
                </ul>
            </div>
        </div>
    }
    else
    {
        @Html.Partial("_NoData")
    }
</div>

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailExteriorContent.cshtml
@using Vienauto.Mobile.Models.View
@model ExteriorModelDetail

@if (Model != null)
{
    @*<div class="embed-responsive embed-responsive-16by9" style="display: none;">
        @Html.Raw(Model.FlashExterior)
    </div>
    <div class="row-end">
    </div>*@
    @Html.Partial("_Inform")
    <div class="row">
        <div class="col-md-6">
            <ul class="list">
                <li>Thông số lốp trước: @Model.FrontTires</li>
                <li>Thông số lốp sau: @Model.BackTires</li>
                <li>Thông số mâm: @Model.Wheels</li>
                <li>Cửa sổ trời: @Model.SunRoof</li>
                <li>Loại cửa sau: @Model.BackWindowType</li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul class="list">
                <li>Sổ cửa: @Model.NumberOfDoors</li>
                <li>Kính hậu: @Model.RearviewMirror</li>
                <li>Xông kính: @Model.HeatedDoorMirror</li>
                <li>Cảm biến mưa: @Model.WindshieldWipes</li>
                <li>Hệ thống nâng hạ gầm: @Model.LiftingSystem</li>
            </ul>
        </div>
    </div>
}
else
{
    @Html.Partial("_NoData")
}

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailInteriorContent.cshtml
@using Vienauto.Mobile.Models.View
@model InteriorModelDetail

@if (Model != null)
{
    @*<div class="embed-responsive embed-responsive-16by9" style="display: none;">
        @Html.Raw(Model.FlashInterior)
    </div>
    <div class="row-end">
    </div>*@
    @Html.Partial("_Inform")
    <div class="row">
        <div class="col-md-6">
            <ul class="list">
                <li>
                    Điều hòa trước:
                    @Model.FrontAirConditioning
                </li>
                <li>
                    Điều hòa sau:
                    @Model.BackAirConditioning
                </li>
                <li>
                    Bộ lọc không khí:
                    @Model.AirFilter
                </li>
                <li>Chỗ ngồi: @Model.Seating</li>
                <li>Loại ghế trước: @Model.FrontSeatType</li>
                <li>Gội đầu: @Model.Shampoo</li>
                <li>La bàn: @Model.Compass</li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul class="list">
                <li>Đồng hồ: @Model.Clocks</li>
                <li>Ổ cắm điện (V): @Model.DCPowerOutlet</li>
                <li>Máy đo tốc độ: @Model.Tachometer</li>
                <li>Máy đo nhiệt độ nước: @Model.WaterTempGauges</li>
                <li>Máy cảnh báo nhiên liệu: @Model.LowFuelWarning</li>
                <li>Hiển thị nhiệt độ ngoài: @Model.DisplayOutsideTemp</li>
            </ul>
        </div>
    </div>
}
else
{
    @Html.Partial("_NoData")
}

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailOverviewContent.cshtml
@using Vienauto.Mobile.Models.View
@model OverviewModelDetail

@if (Model != null && !string.IsNullOrEmpty(Model.Introduction))
{
    <div>
        @Html.Raw(@Model.Introduction)
    </div>
}
else
{
    @Html.Partial("_NoData")
}

Vienauto Web/Vienauto.Mobile/Views/Sell/_SellDetailSafetyContent.cshtml
@using Vienauto.Mobile.Models.View
@model SafetyModelDetail

<div class="pad-box">    
    @if (Model != null)
    {
        @Html.Partial("_Inform")
        <div class="row">
            <div class="col-md-6">
                <ul class="list">
                    <li>Túi khí trước: @Model.FrontAirbag</li>
                    <li>Túi khí bên: @Model.SideAirbag</li>
                    <li>Túi khí sau: @Model.BackAirbag</li>
                    <li>Đèn pha: <span class="upperName">@Model.HeadLights</span></li>
                    <li>Kiểm soát ánh sáng: @Model.ExteriorLightControl</li>
                    <li>Chiếu sáng ban ngày: @Model.DayLights</li>
                    <li>Đèn chiếu hậu: @Model.LedTailLights</li>
                    <li>Hỗ trợ đỗ xe: @Model.ParkingAssist</li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list">
                    <li>Hệ thống báo động: @Model.AlarmSystem</li>
                    <li>Hệ thống khóa cửa: @Model.DoorLockSystem</li>
                    <li>Khóa an toàn: @Model.ChildLock</li>
                    <li>Hệ thống chống trộm: @Model.AntiTheftSystem</li>
                    <li>Cảnh báo áp suất thấp: @Model.LowPressureWarning</li>
                    <li>Loại phanh: @Model.Brakes</li>
                    <li>Hệ thống phanh ABS: @Model.ABSBrakes</li>
                    <li>Hỗ trợ phanh: <span class="upperName">@Model.BrakeAssist</span></li>
                </ul>
            </div>
        </div>
    }
    else
    {
        @Html.Partial("_NoData")
    }
</div>